### PR TITLE
Release v2.6.0

### PR DESCRIPTION
**Pull request by domoscargin**
🆕 New features:

  - The Header component now supports active nav items [PR #207](https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/207)
    - The current active path can be passed into the component call:
      ```
      {{ dmHeader({
        "role": "supplier",
        "active": request.path
      })}}
      ```

### CODE REVIEW

**Review by lfdebrux — APPROVED** [review]

**Comment by domoscargin** [comment]
😬 

Is something up with Travis?

**Comment by lfdebrux** [comment]
It says it's fine on the status page 🤔 https://www.traviscistatus.com/

**Comment by domoscargin** [comment]
Hmm, this was inconclusive: https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/210

Not sure how I'd check it was consistently working.

**Comment by domoscargin** [comment]
@bjgill - this is passing here and locally for me - hopefully fixed by the Jest bump, but could you run locally just for sanity?

**Comment by bjgill** [comment]
Ran `npm install` and `npm test`. Still getting failures about half the time I run the tests:

```
Summary of all failing tests
 FAIL  src/digitalmarketplace/components/search-box/search-box.test.js (9.277 s)
  ● /components/search-box › /components/search-box/preview › when JavaScript is available › when the search box is interacted with › applies the focus style on focus and removes it on blur

    Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:27:45)
```

**Comment by domoscargin** [comment]
I'm going to merge this so we don't let it block our current work, and raise an issue with everything we know.

**Pull request merged**
