### PR TITLE
Github Actions CI

### PR DESCRIPTION
**Pull request by aliuk2012**
Add basic github action

### CODE REVIEW

**Comment by lfdebrux** [comment]
Neat!

This gets run on push, does that mean it runs against every branch? Does it get run as a PR check?

What's the timeliness of the build? Does GitHub put any limit on how many actions you run or how often?

A bit unsure about the support matrix though; does govuk-frontend support Node 12? If they don't then we shouldn't try to either.

**Comment by aliuk2012** [comment]
1. Yes, it gets un against every branch. It does get run as a PR check (See this PR successful checks as an example and [here is the job](https://github.com/alphagov/digitalmarketplace-govuk-frontend/runs/268847486))

2. For the moment it seems pretty quick but we do not have a lot of tests at the moment 😄. As for limits, you can find that [here](https://help.github.com/en/github/automating-your-workflow-with-github-actions/about-github-actions#usage-limits)

I don't think it hurts to test our code with Node 12. Node 12 is the new recommended LTS. Node 10 goes into maintenance mode from April next year. ([See this calendar](https://nodejs.org/en/about/releases/)

**Comment by katstevens** [comment]
Is this intended as a substitute for Travis? How does it compare (pros/cons)? I'd rather keep our tooling consistent across repos but if we gain functionality we can consider rolling this out elsewhere.

Testing against both Node 10 and 12 seems sensible - we had parallel Python 2/3 Travis checks on some of our repos before we dropped Py2 support.

**Comment by lfdebrux** [comment]
> I don't think it hurts to test our code with Node 12. Node 12 is the new recommended LTS. Node 10 goes into maintenance mode from April next year. (See this calendar

My concern is that GOV.UK Frontend isn't tested against Node 12, and specifically says that in it's `package.json` that it only support Node 10.15.1. Does that mean we might end up in a situation where our tests fail on Node 12 because of bugs in GOV.UK Frontend?

**Comment by aliuk2012** [comment]
> Is this intended as a substitute for Travis? How does it compare (pros/cons)? I'd rather keep our tooling consistent across repos but if we gain functionality we can consider rolling this out elsewhere.
> 
> Testing against both Node 10 and 12 seems sensible - we had parallel Python 2/3 Travis checks on some of our repos before we dropped Py2 support.

It can be a replacement for Travis and potentially other things like Jenkins too.
Pay are using it for some testing and deployment.

### Examples
https://github.com/alphagov/pay-tech-docs/actions
https://github.com/alphagov/pay-tech-docs/blob/master/.github/workflows/main.yml

https://github.com/alphagov/pay-product-page/actions?workflow=new-release
https://github.com/alphagov/pay-product-page/blob/master/.github/workflows/release.yml

https://github.com/alphagov/pay-frontend/actions?workflow=product-pages
https://github.com/alphagov/pay-frontend/blob/master/.github/workflows/product-page.yml

**Comment by aliuk2012** [comment]
> > I don't think it hurts to test our code with Node 12. Node 12 is the new recommended LTS. Node 10 goes into maintenance mode from April next year. (See this calendar
> 
> My concern is that GOV.UK Frontend isn't tested against Node 12, and specifically says that in it's `package.json` that it only support Node 10.15.1. Does that mean we might end up in a situation where our tests fail on Node 12 because of bugs in GOV.UK Frontend?

GOV.UK Frontend does not include their test suit in the package so we will not be able to run their test suite with ours. 

Let's see how it goes with Node 12 testing. If it does become a problem we can always remove it from the matrix.

**Comment by lfdebrux** [comment]
I assume you removed the scripts from Travis because it does it automatically out-of-the-box?

**Comment by aliuk2012** [comment]
Yes, Travis uses `npm ci` and  `npm test` as default scripts

**Pull request merged**
